source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KeyboardLayoutGuide_Example' do

  pod 'KeyboardLayoutGuide', :path => '../'
 
  target 'KeyboardLayoutGuide_Tests' do
  
    inherit! :search_paths

  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

