source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KeyboardLayoutGuide_Example' do

  pod 'KeyboardLayoutGuide', :path => '../'
 
  target 'KeyboardLayoutGuide_Tests' do
  
    inherit! :search_paths

  end

end
